name: Auto Comment on issue

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
  
    steps:
      - name: Add comment to new issues
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.issues.createComment
            ({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you for opening this issue!ðŸš€ We will look into it as soon as possibleâœ¨.'
            });